---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - wget
      - tar
    state: present

- name: Create a user for Node Exporter
  user:
    name: node_exporter
    shell: /bin/false

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

- name: Move Node Exporter binary to the correct location
  command: mv /usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: /usr/local/bin/node_exporter

- name: Set correct permissions for Node Exporter binary
  file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Create Node Exporter systemd service file
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable Node Exporter service
  systemd:
    name: node_exporter
    enabled: yes

- name: Start Node Exporter service
  systemd:
    name: node_exporter
    state: started
